### PR TITLE
feat: remove jsdelivr

### PR DESCRIPTION
**Pull request by 100gle**
Why?

Sometimes the target CDN resources may be inaccessible due to network issues or CDN service instability. Therefore, I prefer to store them in a local folder.

### CODE REVIEW

**Comment by laike9m** [comment]
LGTM. Could you take a look at why tests won't pass? Thanks

**Comment by 100gle** [comment]
> Could you take a look at why tests won't pass? Thanks
> 
> Also, isn't CDN preferred in most cases? If there are accessbility issues from China, we can switch to a better CDN另外，大多数情况下 CDN 不是首选吗？如果来自中国的访问存在问题，我们可以切换到更好的 CDN

I don't know why CI failed. In fact, All test cases can be passed in my local machine. It seems to be raised due to lacked GitHub machine resources. Because we use the pytest-xdist library to spawn all test cases to individual worker. Maybe we can handle this by clicking re-run button. XD

Yeah, I prefer to use CDN. But I don't know which CDN can service both of mainland and oversea. 👀

**Comment by laike9m** [comment]
Just ran the test using http://www.chinafirewalltest.com/
We can see if alternatives exist first, if not, can move them to be local

- cdnjs.cloudflare.com ✅

   image

- https://fonts.googleapis.com ❌

   image

-  https://fonts.gstatic.com ❌
    
    image

- https://cdn.jsdelivr.net ❌
   
   image

**Comment by 100gle** [comment]
> Just ran some test using http://www.chinafirewalltest.com/
> 
> * cdnjs.cloudflare.com ✅
>    image
> * https://fonts.googleapis.com ❌
>    image
> * https://fonts.gstatic.com ❌
>    image
> * https://cdn.jsdelivr.net ❌
>    image
> 
> For replacements
> 
> * https://cdnjs.com/libraries/canvas-confetti (currently uses jsdelivr)
> * https://cdnjs.com/libraries/picocss (currently uses jsdelivr)
> * Google fonts 反代 & 镜像
>   
>   * https://u.sb/css-cdn/
>   * https://mirror.sjtu.edu.cn/docs/google-fonts
> 
> Could you try and see if they work?

Sadly, the CDN version of canvas-confetti seems to have a bug and cannot be used even being imported. If you don't want to pull the JS files locally and also want to avoid using jsdelivr, the only option would be to remove the confetti feature. 😢

**Comment by laike9m** [comment]
We can put js-confetti locally, since it's quite small 🙂

**Comment by 100gle** [comment]
@laike9m ready for review

**Pull request merged**
