### PR TITLE
new challenge: NoReturn(advanced)

### PR DESCRIPTION
**Pull request by frostming**
Signed-off-by: Frost Ming <me@frostming.com>

### CODE REVIEW

**Comment by F-park** [comment]
Starting in Python 3.11, the [Never](https://docs.python.org/3/library/typing.html#typing.Never) type should be used for this concept instead. Type checkers should treat the two equivalently.

Since we had [never](https://python-type-challenges.zeabur.app/advanced/never) and [never2](https://python-type-challenges.zeabur.app/advanced/never2),it is necessary to add `NoReturn` for challenge?

**Comment by laike9m** [comment]
I have the same question as F-park

**Comment by frostming** [comment]
I am okay not adding this. Thanks.

**Comment by laike9m** [comment]
Thanks for understanding.

**Pull request closed without merging**
