### PR TITLE
feat: provide an alternative traditional requirements file for user

### PR DESCRIPTION
**Pull request by 100gle**

### CODE REVIEW

**Comment by laike9m** [comment]
Thanks for adding instructions for running it locally, this is something I also plan to do, glad to get some help.

@frostming I know PDM supports exporting `requirements.txt`, but do you think this is a good idea?

**Comment by frostming** [comment]
I suggest [autoexport](https://github.com/pdm-project/pdm-autoexport) plugin and [`pdm.plugins`](https://pdm.fming.dev/latest/dev/write/#specify-the-plugins-in-project) table to avoid manual update for this file. @100gle Could you update the PR?

**Comment by 100gle** [comment]
> I suggest [autoexport](https://github.com/pdm-project/pdm-autoexport) plugin and [`pdm.plugins`](https://pdm.fming.dev/latest/dev/write/#specify-the-plugins-in-project) table to avoid manual(手动) update for this file. @100gle Could you update the PR?我建议自动导出插件和 `pdm.plugins` 表以避免手动更新此文件。 @100gle 你能更新一下 PR 吗？

Sure. let me figure out how to use them firstly. 🤣

**Comment by 100gle** [comment]
@frostming I have updated the PR and add configuration to `pyproject.toml`. Please tell me if there is any issue.

**Comment by frostming** [comment]
> @frostming I have updated the PR and add configuration to `pyproject.toml`. Please tell me if there is any issue.

please add following section in `pyproject.toml`:

```toml
[tool.pdm]
plugins = ["pdm-autoexport"]
```

**Comment by 100gle** [comment]
> ```toml
> [tool.pdm]
> plugins = ["pdm-autoexport"]
> ```

Done. @frostming

**Review by frostming — APPROVED** [review]

**Comment by laike9m** [comment]
Thank you both! This looks great

**Pull request merged**
