### PR TITLE
add advanced solutions

### PR DESCRIPTION
**Pull request by nobod4t**
#19

### CODE REVIEW

**Comment by laike9m** [comment]
Thank you for your time and contribution! Have you double checked all the solutions work as expected?

**Comment by nobod4t** [comment]
@laike9m I would like to chech the solutions programatically. I guess we can do this, right?
I did not figure this out yet. Will see this.

**Comment by laike9m** [comment]
> @laike9m I would like to chech the solutions programatically. I guess we can do this, right? I did not figure this out yet. Will see this.

Adding test for solutions is on the roadmap. For now you have to test it manually using pyright CLI, [running type-challenge locally ](https://github.com/laike9m/Python-Type-Challenges#how-to-run-locally), or using https://pyright-play.net/

**Comment by nobod4t** [comment]
OK.  if my vi uses pywrite as plugin and if not error alerts it would be fine.

**Comment by laike9m** [comment]
> OK. if my vi uses pywrite as plugin and if not error alerts it would be fine.

Well, it should raise error on `# expect-type-error`, otherwise the solution is incorrect. Let me know when you've verified it, then I'll approve.

**Comment by nobod4t** [comment]
I checked them all. Please review.

**Comment by laike9m** [comment]
Thank you so much!

**Pull request merged**
