### PR TITLE
refactor(ui): refactor sidebar for challenge page

### PR DESCRIPTION
**Pull request by 100gle**

### CODE REVIEW

**Comment by laike9m** [comment]
I'm interested to learn what you have in mind for the sidebar (before you actually create the PR). If you have a screenshot, prototype that would work best, but just describing it works too.

**Comment by 100gle** [comment]
> I'm interested to learn what you have in mind for the sidebar (before you actually create the PR). If you have a screenshot, prototype that would work best, but just describing it works too.我有兴趣了解您对侧边栏的想法（在实际创建 PR 之前）。如果您有屏幕截图、原型，效果最好，但仅描述它也可以。

On desktop, the Sidebar doesn't have many changes, only the removal of the collapse functionality, allowing users to browse all challenges by scrolling. But on mobile viewport, the Sidebar is placed inside a **Drawer**, which can be controlled by a Menu icon to slide in or out.

**Comment by laike9m** [comment]
Awesome. Do you have a screenshot of how the drawer looks like?

**Comment by 100gle** [comment]
> Awesome. Do you have a screenshot of how the drawer looks like?

Yeah, the very basic prototype looks like: 

prototype

But there are a lots of details need to improve. Maybe I can finish them in this weekend 🤣

**Comment by 100gle** [comment]
@laike9m All is ready. 

Now, sidebar looks better.

屏幕录制2023-11-24 21 45 05

**Comment by laike9m** [comment]
Thanks! Some feedbacks

- The routing of challenge is wrong. Now it should be `/level/name` instead of `/challenge/name`
- font size and weight, I suggest `font-size: 35px; font-weight: 700;` to the maximum
- Before there's some space above the title, which feels better. Maybe we can try align the height of "BASIC" and chanllege title?
  - before image
  - after image

- Like my previous feedback, I still feel the space in the challenge list is too big. I'm ok to make it larger than before, but please make it smaller
   
  image

**Comment by 100gle** [comment]
@laike9m I have adjusted some details correspondingly, please run locally and check again~

**Comment by laike9m** [comment]
Overall looks good now!

One remaining issue and we should be good to merge:
When on mobile, it's not clear users can click and open the drawer. Could you add some text like below? Drawer icon should be on the very left, text is next to it

image

**Comment by 100gle** [comment]
> Overall looks good now!
> 
> 
> 
> One remaining issue and we should be good to merge:
> 
> When on mobile, it's not clear users can click and open the drawer. Could you add some text like below? Drawer icon should be on the very left, text is next to it
> 
> 
> 
> image
> 
> 

In my opinions, I prefer to keep menu（drawer toggle） icon in the header rather than left edge. 

Because the horizontal spaces on mobile are limited and edge touching may not work well for some devices with curved screen or with phone case.

**Comment by 100gle** [comment]
By the way, single theme switcher looks not good 🤣

**Comment by laike9m** [comment]
Merged, thanks again!

**Pull request merged**
