### PR TITLE
fix: Make sure indentation in existing code and code editor are consistent

### PR DESCRIPTION
**Pull request by Zheaoli**
Signed-off-by: Manjusaka <me@manjusaka.me>

### CODE REVIEW

**Review by 100gle — APPROVED** [review]
LGTM

**Comment by laike9m** [comment]
2 spaces is intentional, reason being that width of code editors is already pretty small.

image

**Comment by laike9m** [comment]
I think the right fix should be to change challenge code to use two spaces (or tab)

**Comment by laike9m** [comment]
Actually thinking twice, switching to 4 spaces tab should be fine, as user code most likely won't contain too many chars in a single line (as they're mostly definitions)

**Pull request merged**
